name: Chunky
game_type: jeopardy
categories:
  - name: Category 1
    questions:
      - question: Question 1
        answer: Answer 1
        points: 100
      - question: Question 2
        answer: Answer 2
        points: 200
      - question: Question 3
        answer: Answer 3
        points: 300
      - question: Question 4
        answer: Answer 4
        points: 400
      - question: Question 5
        answer: Answer 5
        points: 500
  - name: Category 2
    questions:
      - question: Question 1
        answer: Answer 1
        points: 100
      - question: Question 2
        answer: Answer 2
        points: 200
      - question: Question 3
        answer: Answer 3
        points: 300
      - question: Question 4
        answer: Answer 4
        points: 400
      - question: Question 5
        answer: Answer 5
        points: 500
  - name: Category 3
    questions:
      - question: Question 1
        answer: Answer 1
        points: 100
      - question: Question 2
        answer: Answer 2
        points: 200
      - question: Question 3
        answer: Answer 3
        points: 300
      - question: Question 4
        answer: Answer 4
        points: 400
      - question: Question 5
        answer: Answer 5
        points: 500
  - name: Category 4
    questions:
      - question: Question 1
        answer: Answer 1
        points: 100
      - question: Question 2
        answer: Answer 2
        points: 200
      - question: Question 3
        answer: Answer 3
        points: 300
      - question: Question 4
        answer: Answer 4
        points: 400
      - question: Question 5
        answer: Answer 5
        points: 500
  - name: Category 5
    questions:
      - question: Question 1
        answer: Answer 1
        points: 100
      - question: Question 2
        answer: Answer 2
        points: 200
      - question: Question 3
        answer: Answer 3
        points: 300
      - question: Question 4
        answer: Answer 4
        points: 400
      - question: Question 5
        answer: Answer 5
        points: 500
